# Generated by Django 3.1.5 on 2021-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='valid python', max_length=122),
            preserve_default=False,
        ),
    ]
