# Generated by Django 3.1.5 on 2021-01-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
